name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: googleapis/release-please-action@v5
        with:
          release-type: ruby
          version-file: lib/binance/usdm/version.rb
